# Generated by Django 4.2 on 2024-04-14 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livero', '0006_hospitals_laps_doctors_latitude_doctors_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readings',
            name='liver',
        ),
    ]
